routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('guest')->get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('admin_or_manager:admin,manager')->group(function(){

    Route::get('seed', 'SeedsController@index');
    Route::resource('destinations', 'DestinationController');
    Route::resource('groups', 'GroupController');
    Route::get('customers', 'UserController@customer');
    Route::get('groups/{group}/payments/create', 'PaymentController@groupPaymentFrom')->name('groups.payments.create');
    Route::post('groups/{group}/payments', 'PaymentController@store')->name('groups.payments.store');
    Route::get('groups/{group}/payments/{payment}/edit', 'PaymentController@edit')->name('groups.payment.edit');
    Route::get('groups/{group}/payments/{payment}', 'PaymentController@show')->name('groups.payment.show');
    Route::post('groups/{group}/payments/{payment}', 'PaymentController@update')->name('groups.payment.update');
    Route::get('groups/{group}/customers/json', 'GroupController@customerJson')->name('groups.customers.json');

    Route::get('payments/{payment}/download', 'PaymentController@downloadProof')->name('payments.proof.download');

    Route::get('customers', 'UserController@index')->name('customers.index');
    Route::get('customers/json', 'UserController@userJson')->name('customers.json');
    Route::get('customers/create', 'UserController@create')->name('customers.create');
    Route::post('customers', 'UserController@store')->name('customers.store');
    Route::post('customer-balance', 'PaymentController@customerBalance')->name('customers.balance');
    Route::post('get-customer-flight-number', 'FlightController@getCustomerFlight')->name('customers.flight');
    Route::get('groups/{group}/customers/show', 'CustomerGroupController@getCustomers')->name('groups.customers');
    Route::post('groups/{group}/customer/flight', 'CustomerGroupController@storeCustomerFlight')->name('groups.customers.flight.store');

});


Route::group(['prefix' => 'admin'],function () {
    Route::get('register', 'AdminController@create')->name('admin.register');
    Route::post('register', 'AdminController@store')->name('admin.register.store');
    Route::get('login', 'Auth\Admin\LoginController@login')->name('admin.auth.login');
    Route::post('login', 'Auth\Admin\LoginController@loginAdmin')->name('admin.auth.loginAdmin');
    Route::post('logout', 'Auth\Admin\LoginController@logout')->name('admin.auth.logout');
});

Route::group(['prefix' => 'admin','middleware' => 'admin'],function () {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('managers/create', 'ManagerController@create')->name('managers.create');
    Route::get('managers', 'ManagerController@index')->name('managers.index');
    Route::post('managers', 'ManagerController@managerStore')->name('managers.store');
    Route::get('managers/{manager}/edit', 'ManagerController@edit')->name('managers.edit');
    Route::put('managers/{manager}/status', 'ManagerController@status')->name('managers.status');
    Route::put('managers/{manager}', 'ManagerController@update')->name('managers.update');
    Route::delete('managers/{manager}', 'ManagerController@destroy')->name('managers.destroy');
});

Route::prefix('manager')->group(function () {
    Route::get('/', 'ManagerController@index')->name('manager.dashboard');
    Route::get('dashboard', 'ManagerController@index')->name('manager.dashboard');
    Route::get('register', 'ManagerController@create')->name('manager.register');
    Route::post('register', 'ManagerController@store')->name('manager.register.store');
    Route::get('login', 'Auth\Manager\LoginController@login')->name('manager.auth.login');
    Route::post('login', 'Auth\Manager\LoginController@loginAdmin')->name('manager.auth.loginManager');
    Route::post('logout', 'Auth\Manager\LoginController@logout')->name('manager.auth.logout');
});



Route::get('/clear-cache', function(){
    $re = \Artisan::call('cache:clear');
    $re = \Artisan::call('config:cache');
    return $re;
});

Route::get('/migrate', function(){
    $re = \Artisan::call('migrate');
    return $re;
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <script>
        window.user = {!!  json_encode(auth()->user())  !!};
    </script>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ route('home') }}">
                {{ config('app.name', 'Travel Groups') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">  
                    @if(Auth::guard('admin')->check())
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>{{ __('app.managers') }}<span class="caret"></span></a>
                            <div class="dropdown-menu dropdown-menu-right"></span>
                                <a class="dropdown-item" href="{{ route('managers.create') }}">{{ __('app.create_manager') }}</a>
                                <a class="dropdown-item" href="{{ route('managers.index') }}">{{ __('app.manager_list') }}</a>
                            </div>
                        </li>
                    
                        <li class="nav-item dropdown">
                            <a id="dropdownDestination" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ __('app.destinations') }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownDestination">
                                <a class="dropdown-item" href="{{ route('destinations.create') }}">{{ __('app.new_destinations') }}</a>
                                <a class="dropdown-item" href="{{ route('destinations.index') }}">{{ __('app.destinations_list') }}</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ __('app.groups') }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('groups.index') }}">{{ __('app.groups_list') }}</a>
                                <a class="dropdown-item" href="{{ route('groups.create') }}">{{ __('app.new_group') }}</a>
                            </div>
                        </li>
                    @endif
                </ul>
                <!-- <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Destinations <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('destinations.index') }}">Destinations List</a>
                            <a class="dropdown-item" href="{{ route('destinations.create') }}">Add Destination</a>
                        </div>
                    </li>
                    
                </ul> -->

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        <li class="nav-item">
                            @if (Route::has('register'))
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            @endif
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->first_name }} {{ Auth::user()->last_name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @if(session()->has('message'))
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="alert alert-success">
                            {{ session()->get('message') }}
                        </div>
                    </div>
                </div>
            </div>
        @endif

        @if(session()->has('error'))
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="alert alert-danger">
                            {{ session()->get('error') }}
                        </div>
                    </div>
                </div>
            </div>
        @endif

        @yield('content')
    </main>

 </div>

    @yield('footer-script')
</body>
</html>