routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('guest')->get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('admin_or_manager:admin,manager')->group(function(){

    Route::get('seed', 'SeedsController@index');
    Route::resource('destinations', 'DestinationController');
    Route::resource('groups', 'GroupController');
    Route::get('customers', 'UserController@customer');
    Route::get('groups/{group}/payments/create', 'PaymentController@groupPaymentFrom')->name('groups.payments.create');
    Route::post('groups/{group}/payments', 'PaymentController@store')->name('groups.payments.store');
    Route::get('groups/{group}/payments/{payment}/edit', 'PaymentController@edit')->name('groups.payment.edit');
    Route::get('groups/{group}/payments/{payment}', 'PaymentController@show')->name('groups.payment.show');
    Route::post('groups/{group}/payments/{payment}', 'PaymentController@update')->name('groups.payment.update');
    Route::get('groups/{group}/customers/json', 'GroupController@customerJson')->name('groups.customers.json');

    Route::get('payments/{payment}/download', 'PaymentController@downloadProof')->name('payments.proof.download');

    Route::get('customers', 'UserController@index')->name('customers.index');
    Route::get('customers/json', 'UserController@userJson')->name('customers.json');
    Route::get('customers/create', 'UserController@create')->name('customers.create');
    Route::post('customers', 'UserController@store')->name('customers.store');
    Route::post('customer-balance', 'PaymentController@customerBalance')->name('customers.balance');
    Route::post('get-customer-flight-number', 'FlightController@getCustomerFlight')->name('customers.flight');
    Route::get('groups/{group}/customers/show', 'CustomerGroupController@getCustomers')->name('groups.customers');
    Route::post('groups/{group}/customer/flight', 'CustomerGroupController@storeCustomerFlight')->name('groups.customers.flight.store');

});


Route::group(['prefix' => 'admin'],function () {
    Route::get('register', 'AdminController@create')->name('admin.register');
    Route::post('register', 'AdminController@store')->name('admin.register.store');
    Route::get('login', 'Auth\Admin\LoginController@login')->name('admin.auth.login');
    Route::post('login', 'Auth\Admin\LoginController@loginAdmin')->name('admin.auth.loginAdmin');
    Route::post('logout', 'Auth\Admin\LoginController@logout')->name('admin.auth.logout');
});

Route::group(['prefix' => 'admin','middleware' => 'admin'],function () {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('managers/create', 'ManagerController@create')->name('managers.create');
    Route::get('managers', 'ManagerController@index')->name('managers.index');
    Route::post('managers', 'ManagerController@managerStore')->name('managers.store');
    Route::get('managers/{manager}/edit', 'ManagerController@edit')->name('managers.edit');
    Route::put('managers/{manager}/status', 'ManagerController@status')->name('managers.status');
    Route::put('managers/{manager}', 'ManagerController@update')->name('managers.update');
    Route::delete('managers/{manager}', 'ManagerController@destroy')->name('managers.destroy');
});

Route::prefix('manager')->group(function () {
    Route::get('/', 'ManagerController@index')->name('manager.dashboard');
    Route::get('dashboard', 'ManagerController@index')->name('manager.dashboard');
    Route::get('register', 'ManagerController@create')->name('manager.register');
    Route::post('register', 'ManagerController@store')->name('manager.register.store');
    Route::get('login', 'Auth\Manager\LoginController@login')->name('manager.auth.login');
    Route::post('login', 'Auth\Manager\LoginController@loginAdmin')->name('manager.auth.loginManager');
    Route::post('logout', 'Auth\Manager\LoginController@logout')->name('manager.auth.logout');
});



Route::get('/clear-cache', function(){
    $re = \Artisan::call('cache:clear');
    $re = \Artisan::call('config:cache');
    return $re;
});

Route::get('/migrate', function(){
    $re = \Artisan::call('migrate');
    return $re;
});

app/Models/Destination.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Destination extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name', 'city', 'max_capacity', 'price', 'active', 'created_by'
    ];

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function groups()
    {
        return $this->hasMany(Group::class);
    }
}

app/Http/Controllers/DestinationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Destination;
use Illuminate\Http\Request;
use Illuminate\Validation\Validator;

class DestinationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();
        if(auth()->guard('admin')->check())
        {
            $user = auth()->guard('admin')->user();
        }
        if (request()->wantsJson())
        {
            /*return Destination::select('id', 'name')->get();*/
            return $user->destinations;
        }
        return view('destinations.index', ['records' => $user->destinations()->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('destinations.create', ['destination' => new Destination()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => 'required',
            'max_capacity' => 'required|integer',
            'city' => 'required|string',
            'price' => 'required|integer'
        ]);

        $destination = new Destination($request->all());
        auth()->user()->destinations()->save($destination);

        return redirect()->route('destinations.index')->with('message', 'Destinations Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Destination  $destination
     * @return \Illuminate\Http\Response
     */
    public function show(Destination $destination)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Destination  $destination
     * @return \Illuminate\Http\Response
     */
    public function edit(Destination $destination)
    {
        return view('destinations.create', ['destination' => $destination]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Destination  $destination
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Destination $destination)
    {
        $request->validate([
            'name' => 'required',
            'max_capacity' => 'required|integer',
            'city' => 'required|string',
            'price' => 'required|integer'
        ]);

        $destination->fill($request->all())->save();

        return redirect()->route('destinations.index')->with('message', 'Destinations Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Destination $destination
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Destination $destination)
    {
        if($destination->groups()->exists())
        {
            return redirect()->route('destinations.index')->with('error', 'Destination has one or more Groups related please delete group first.');
        }

        $destination->delete();
        return redirect()->route('destinations.index')->with('message', 'Destinations Deleted Successfully');
    }
}

resources/views/destinations/create.blade.php
@extends('layouts.app')

@section('page_title')
    <h3 class="k-content__head-title">{{ __('app.new_destinations') }}</h3>
@endsection

@section('breadcrumbs')
    {!! Breadcrumbs::render('destinations.create', $destination->id) !!}
@endsection

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('app.new_destinations') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form method="POST" class="k-form" action="{{ $destination->id? route('destinations.update', ['destination' => $destination->id]): route('destinations.store') }}">
                    @csrf
                    @if($destination->id) @method('put') @endif

                    <div class="k-portlet__body">

                        <div class="form-group validated">
                            <label for="name">{{ __('form.name') }}</label>
                            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $destination->name) }}" required autofocus>
                            @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group validated">
                            <label for="city">{{ __('form.city') }}</label>
                            <input id="city" type="text" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city', $destination->city) }}" required>
                            @if ($errors->has('city'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('city') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group validated">
                            <label for="max_capacity">{{ __('form.max_capacity') }}</label>
                            <input id="max_capacity" type="text" class="form-control{{ $errors->has('max_capacity') ? ' is-invalid' : '' }}" name="max_capacity" value="{{ old('max_capacity', $destination->max_capacity) }}" required>
                            @if ($errors->has('max_capacity'))
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('max_capacity') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <div class="form-group validated">
                            <label for="price">{{ __('form.price') }}</label>
                            <input id="price" type="number" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" name="price" value="{{ old('price', $destination->price) }}" required>
                            @if ($errors->has('price'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('price') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="k-portlet__foot">
                        <div class="k-form__actions k-form__actions">
                            <button type="submit" class="btn btn-brand">{{ __('form.submit') }}</button>
                            <a href="{{ route('destinations.index') }}" class="btn btn-secondary">{{ __('form.cancel') }}</a>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- <div class="row">
        <div class="col-lg-12">
            <div class="k-portlet">
                <div class="k-portlet__head">
                    <div class="k-portlet__head-label">
                        <h3 class="k-portlet__head-title"></h3>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

@endsection

resources/views/destinations/index.blade.php
@extends('layouts.app')

@section('footer_scripts')
    <!--begin::Page Vendors -->
    <script src="{{ asset('assets/vendors/custom/datatables/datatables.bundle.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/demo/default/custom/components/datatables/basic/basic.js') }}" type="text/javascript"></script>
@endsection

@section('page_title')
    <h3 class="k-content__head-title">{{ __('app.destinations_list') }}</h3>
@endsection

@section('breadcrumbs')
    {!! Breadcrumbs::render('destinations') !!}
@endsection

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{ __('app.destinations_list') }}
                    <a href="{{ route('destinations.create') }}" class="btn btn-success float-right">{{ __('app.new_destinations') }}</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="table table-striped- table-bordered table-hover table-checkable" id="k_table_1">
                    <thead>
                    <tr>
                        <th>{{ __('form.name') }}</th>
                        <th>{{ __('app.city') }}</th>
                        <th>{{ __('app.max_capacity') }}</th>
                        <th>{{ __('app.price') }}</th>
                        <th>{{ __('app.status') }}</th>
                        <th>{{ __('app.action') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($records as $row)
                        <tr>
                            <td>{{ $row->name }}</td>
                            <td>{{ $row->city }}</td>
                            <td>{{ $row->max_capacity }}</td>
                            <td>{{ $row->price }}</td>
                            <td>{{ $row->active }}</td>
                            <td>
                                <!-- <span class="dropdown show">
                                    <a href="#" class="btn btn-sm btn-clean btn-icon btn-icon-md" data-toggle="dropdown" aria-expanded="true">
                                      <i class="la la-ellipsis-h"></i>
                                    </a>
                                    <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end" style="position: absolute; transform: translate3d(-218px, 25px, 0px); top: 0px; left: 0px; will-change: transform;">
                                        <a class="dropdown-item" href="#"><i class="la la-edit"></i> {{ __('app.edit')  }}</a>
                                        
                                    </div>
                                </span> -->
                                <a class="fa fa-edit btn btn-sm btn-outline-info" href="{{ route('destinations.edit', $row->id) }}"></a>
  
                                <a class="fa fa-trash btn btn-sm btn-outline-danger" href="#" onclick="event.preventDefault(); if(confirm('Do you want to delete?')){ document.getElementById('row{{ $row->id }}').submit(); }">
                                    <form action="{{ route('destinations.destroy', $row->id) }}" id="row{{ $row->id }}" class="d-inline" method="post">
                                        @csrf
                                        @method('delete')
                                    </form>
                                    <!-- {{ __('app.delete')  }} -->
                                </a>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection