routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('guest')->get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('admin_or_manager:admin,manager')->group(function(){

    Route::get('seed', 'SeedsController@index');
    Route::resource('destinations', 'DestinationController');
    Route::resource('groups', 'GroupController');
    Route::get('customers', 'UserController@customer');
    Route::get('groups/{group}/payments/create', 'PaymentController@groupPaymentFrom')->name('groups.payments.create');
    Route::post('groups/{group}/payments', 'PaymentController@store')->name('groups.payments.store');
    Route::get('groups/{group}/payments/{payment}/edit', 'PaymentController@edit')->name('groups.payment.edit');
    Route::get('groups/{group}/payments/{payment}', 'PaymentController@show')->name('groups.payment.show');
    Route::post('groups/{group}/payments/{payment}', 'PaymentController@update')->name('groups.payment.update');
    Route::get('groups/{group}/customers/json', 'GroupController@customerJson')->name('groups.customers.json');

    Route::get('payments/{payment}/download', 'PaymentController@downloadProof')->name('payments.proof.download');

    Route::get('customers', 'UserController@index')->name('customers.index');
    Route::get('customers/json', 'UserController@userJson')->name('customers.json');
    Route::get('customers/create', 'UserController@create')->name('customers.create');
    Route::post('customers', 'UserController@store')->name('customers.store');
    Route::post('customer-balance', 'PaymentController@customerBalance')->name('customers.balance');
    Route::post('get-customer-flight-number', 'FlightController@getCustomerFlight')->name('customers.flight');
    Route::get('groups/{group}/customers/show', 'CustomerGroupController@getCustomers')->name('groups.customers');
    Route::post('groups/{group}/customer/flight', 'CustomerGroupController@storeCustomerFlight')->name('groups.customers.flight.store');

});


Route::group(['prefix' => 'admin'],function () {
    Route::get('register', 'AdminController@create')->name('admin.register');
    Route::post('register', 'AdminController@store')->name('admin.register.store');
    Route::get('login', 'Auth\Admin\LoginController@login')->name('admin.auth.login');
    Route::post('login', 'Auth\Admin\LoginController@loginAdmin')->name('admin.auth.loginAdmin');
    Route::post('logout', 'Auth\Admin\LoginController@logout')->name('admin.auth.logout');
});

Route::group(['prefix' => 'admin','middleware' => 'admin'],function () {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('dashboard', 'AdminController@index')->name('admin.dashboard');
    Route::get('managers/create', 'ManagerController@create')->name('managers.create');
    Route::get('managers', 'ManagerController@index')->name('managers.index');
    Route::post('managers', 'ManagerController@managerStore')->name('managers.store');
    Route::get('managers/{manager}/edit', 'ManagerController@edit')->name('managers.edit');
    Route::put('managers/{manager}/status', 'ManagerController@status')->name('managers.status');
    Route::put('managers/{manager}', 'ManagerController@update')->name('managers.update');
    Route::delete('managers/{manager}', 'ManagerController@destroy')->name('managers.destroy');
});

Route::prefix('manager')->group(function () {
    Route::get('/', 'ManagerController@index')->name('manager.dashboard');
    Route::get('dashboard', 'ManagerController@index')->name('manager.dashboard');
    Route::get('register', 'ManagerController@create')->name('manager.register');
    Route::post('register', 'ManagerController@store')->name('manager.register.store');
    Route::get('login', 'Auth\Manager\LoginController@login')->name('manager.auth.login');
    Route::post('login', 'Auth\Manager\LoginController@loginAdmin')->name('manager.auth.loginManager');
    Route::post('logout', 'Auth\Manager\LoginController@logout')->name('manager.auth.logout');
});



Route::get('/clear-cache', function(){
    $re = \Artisan::call('cache:clear');
    $re = \Artisan::call('config:cache');
    return $re;
});

Route::get('/migrate', function(){
    $re = \Artisan::call('migrate');
    return $re;
});

app/Models/Group.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Group extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'destination_id',
        'arrival_date',
        'arrival_hour',
        'out_date',
        'special_requirements',
        'active',
        'created_by'
    ];

    protected $dates = [
        'arrival_date',
        'out_date'
    ];

    public function setArrivalDateAttribute($value)
    {
        $s = explode('/', $value);
        $this->attributes['arrival_date'] = now()->setDate($s[2],$s[1],$s[0]);
    }

    public function setOutDateAttribute($value)
    {
        $s = explode('/', $value);
        $this->attributes['out_date'] = now()->setDate($s[2],$s[1],$s[0]);
    }

    public function customers()
    {
        return $this->belongsToMany(User::class, 'customer_group', 'group_id', 'customer_id')
            ->withPivot('price', 'flight_no', 'arrival_hour');
    }

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function destination()
    {
        return $this->belongsTo(Destination::class);
    }

}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Models\Group;
use Illuminate\Http\Request;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $groups = auth()->user()->groups()->withCount('customers')->with('destination')->get();
        return view('groups.index', compact('groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('groups.create', ['group' => new Group()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'destination_id' => 'required|exists:destinations,id',
            'arrival_date' => 'required|date_format:d/m/Y',
            'out_date' => 'required|date_format:d/m/Y',
            'customers' => 'required|array',
            // 'special_requirements' => 'required',
            'customers.*.name.id' => 'required',
            'customers.*.price' => 'required',
        ]);

        $syncIds = [];
        foreach ($request->customers as $customer)
        {
            $syncIds[$customer['name']['id']] = [ 'price' => $customer['price'] ];
        }

        $group = new Group($request->all());
        auth()->user()->groups()->save($group);
        $group->customers()->sync($syncIds);

        return response()->make(json_encode([
            'status' => 'success',
            'message' => 'Group inserted successfully!',
            'returnUrl' => route('groups.index')
        ]), 201);

        // return redirect()->route('destinations.index')->with('message', 'Destinations Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Request $request
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Group $group)
    {
        if ($request->isXmlHttpRequest())
        {
            $group->load('destination');
            return $group;
        }
        return view('groups.show', compact('group'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Group  $group
     * @return @any
     */
    public function edit(Request $request, Group $group)
    {
        if ($request->isXmlHttpRequest()){
            $group->load('customers');
            return $group;
        }
        return view('groups.create', compact('group'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Group $group)
    {
        $request->validate([
            'destination_id' => 'required|exists:destinations,id',
            'arrival_date' => 'required|date_format:d/m/Y',
            'out_date' => 'required|date_format:d/m/Y',
            'arrival_hour' => 'required',
            // 'special_requirements' => 'required',
            'customers' => 'required|array',
            'customers.*.name.id' => 'required',
            'customers.*.price' => 'required',
        ]);

        $syncIds = [];
        foreach ($request->customers as $customer)
        {
            $syncIds[$customer['name']['id']] = [ 'price' => $customer['price'] ];
        }

        $group->fill($request->all());
        $group->save();
        $group->customers()->sync($syncIds);

        return response()->make(json_encode([
            'status' => 'success',
            'message' => 'Group updated successfully!',
            'returnUrl' => route('groups.index')
        ]), 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Group $group
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Group $group)
    {
        $group->delete();
        return redirect()->route('groups.index')->with('message', 'Group Deleted Successfully');
    }

    /**
     * Return customers for given group.
     *
     * @param  \App\Models\Group  $group
     * @return \Illuminate\Http\Response
     */
    public function customerJson(Group $group)
    {
        return $group->customers;
    }


}

resources/views/groups/create.backup.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ $group->id? 'Edit': 'New' }} Group
                        <a class="btn btn-success float-right" href="{{ route('groups.index') }}">View List</a>
                    </div>

                    <div class="card-body">
                        <form method="POST" action="{{ $group->id? route('groups.update', ['destination' => $group->id]): route('groups.store') }}">
                            @csrf
                            @if($group->id) @method('put') @endif

                            <div class="form-group row">
                                <label for="arrival_date" class="col-md-4 col-form-label text-md-right">Arrival Date</label>

                                <div class="col-md-6">
                                    <input id="arrival_date" type="date" class="form-control{{ $errors->has('arrival_date') ? ' is-invalid' : '' }}" name="arrival_date" value="{{ old('arrival_date', $group->arrival_date? $group->arrival_date->format('Y-m-d'): '') }}" required autofocus>

                                    @if ($errors->has('arrival_date'))
                                        <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('arrival_date') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="out_date" class="col-md-4 col-form-label text-md-right">Out Date</label>

                                <div class="col-md-6">
                                    <input id="out_date" type="date" class="form-control{{ $errors->has('out_date') ? ' is-invalid' : '' }}" name="out_date" value="{{ old('out_date', $group->out_date? $group->out_date->format('Y-m-d'): '') }}" required autofocus>

                                    @if ($errors->has('out_date'))
                                        <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('out_date') }}</strong>
                                </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="go" class="col-md-4 col-form-label text-md-right">Group Owner</label>

                                <div class="col-md-6">
                                    <input id="go" type="text" readonly class="form-control" value="{{ auth()->user()->first_name }} {{ auth()->user()->last_name }}" required>
                                </div>
                            </div>

                            <div>
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Customer</th>
                                        <th>Total Price</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <input type="hidden" v-model="customerValues" name="customers">
                                    <tr v-for="(customer, index) in customers">
                                        <td>
                                            <v-select label="first_name" name="customers[]" :options="options" v-model="customer.name"></v-select>
                                        </td>
                                        <td>
                                            <input type="number" v-model="customer.price" class="form-control">
                                        </td>
                                        <td>
                                            <button class="btn btn-danger" type="button" @click="deleteCustomer(index)" v-if="customers.length>1">-</button>
                                            <button class="btn btn-primary" type="button" @click="addCustomer()">+</button>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/groups/create.blade.php
@extends('layouts.app')

@section('page_title')
    <h3 class="k-content__head-title">{{ __('app.new_group') }}</h3>
@endsection

@section('breadcrumbs')
    {!! Breadcrumbs::render('groups.create', $group->id) !!}
@endsection

@section('content')
    <create-group @if($group->id) group-id="{{ $group->id }}" @endif></create-group>
@endsection

resources/views/groups/index.blade.php
@extends('layouts.app')

@section('footer_scripts')
    <!--begin::Page Vendors -->
    <script src="{{ asset('assets/vendors/custom/datatables/datatables.bundle.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/demo/default/custom/components/datatables/basic/basic.js') }}" type="text/javascript"></script>
@endsection

@section('page_title')
    <h3 class="k-content__head-title">{{ __('app.groups_list') }}</h3>
@endsection

@section('breadcrumbs')
    {!! Breadcrumbs::render('groups') !!}
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    {{ __('app.groups_list') }}
                    <a href="{{ route('groups.create') }}" class="btn btn-success float-right">{{ __('app.new_group') }}</a>
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <table class="table table-striped- table-bordered table-hover table-checkable" id="k_table_1">
                        <thead>
                        <tr>
                            <th>{{ __('app.reference') }}</th>
                            <th>{{ __('app.destinations') }}</th>
                            <th>{{ __('app.arrival_date') }}</th>
                            <th>{{ __('app.out_date') }}</th>
                            <th>{{ __('app.total_clients') }}</th>
                            <th>{{ __('app.action') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($groups as $row)
                            <tr>
                                <td><a href="{{ route('groups.show', ['group'=>$row->id]) }}">{{ $row->id }}</a></td>
                                <td><a href="{{ route('groups.show', ['group'=>$row->id]) }}">{{ $row->destination->name }}</a></td>
                                <td><a href="{{ route('groups.show', ['group'=>$row->id]) }}">{{ $row->arrival_date->format('d/m/Y') }}</a></td>
                                <td><a href="{{ route('groups.show', ['group'=>$row->id]) }}">{{ $row->out_date->format('d/m/Y') }}</a></td>
                                <td><a href="{{ route('groups.show', ['group'=>$row->id]) }}">{{ $row->customers_count }}</a></td>
                                <td>
                                    <a href="{{ route('groups.edit', ['group' => $row->id ]) }}"><i class="fa fa-edit btn btn-outline-info"></i> </a>
                                    <a href="{{ route('groups.payments.create', ['group' => $row->id ]) }}"><i class="fa fa-money btn btn-outline-info"></i> {{-- __('app.payment') --}}</a>
                                    <a href="#" onclick="event.preventDefault(); document.getElementById('row{{ $row->id }}').submit();"><i class="fa fa-trash btn btn-outline-danger"></i>
                                        <form action="{{ route('groups.destroy', $row->id) }}" id="row{{ $row->id }}" class="d-inline" method="post">
                                            @csrf
                                            @method('delete')
                                        </form>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/groups/paymentForm.blade.php
@extends('layouts.app')
@section('page_title')
    <h3 class="k-content__head-title">{{ __('app.register_new_payment') }}</h3>
@endsection

@section('breadcrumbs')
    {!! Breadcrumbs::render('groups.payment', $group) !!}
@endsection
@section('content')
    <group-payment-form group-id="{{ $group->id }}"  @if($payment->id) payment-id="{{ $payment->id }}" @endif></group-payment-form>
@endsection

resources/views/groups/show.blade.php
@extends('layouts.app')

@section('page_title')
    <h3 class="k-content__head-title">{{ __('app.groups') }} {{ $group->destination->name }}</h3>
@endsection

@section('breadcrumbs')
    {!! Breadcrumbs::render('groups.show', $group) !!}
@endsection

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ $group->destination->name }} [{{ $group->out_date->format('m/d/Y') }} - {{ $group->arrival_date->format('m/d/Y') }}]</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <ul class="nav nav-pills nav-tabs-btn" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#k_tabs_8_1" role="tab">
                                <span class="nav-link-icon"><i class="flaticon2-graph-1"></i></span>
                                <span class="nav-link-title">{{ __('app.details') }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#k_tabs_8_2" role="tab">
                                <span class="nav-link-icon"><i class="flaticon2-position"></i></span>
                                <span class="nav-link-title">{{ __('app.clients') }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#k_tabs_8_3" role="tab">
                                <span class="nav-link-icon"><i class="flaticon2-placeholder"></i></span>
                                <span class="nav-link-title">{{ __('app.payment_list') }}</span>
                            </a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="k_tabs_8_1" role="tabpanel">
                            <ul class="list-group">
                                <li class="list-group-item">Destination: {{ $group->destination->name }}</li>
                                <li class="list-group-item">Arrival Date: {{ $group->arrival_date->format('d/m/Y') }}</li>
                                <li class="list-group-item">Out Date: {{ $group->out_date->format('d/m/Y') }}</li>
                                <li class="list-group-item">No. Members: {{ count($group->customers) }}</li>
                                <li class="list-group-item">Owner: {{ $group->creator->first_name }} {{ $group->creator->last_name }}</li>
                            </ul>
                        </div>
                        <div class="tab-pane fade" id="k_tabs_8_2" role="tabpanel">

                            <group-customer-list :group-id="{{ $group->id }}"></group-customer-list>

                        </div>
                        <div class="tab-pane fade" id="k_tabs_8_3" role="tabpanel">
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th>{{ __('app.payment_id') }}</th>
                                        <th>{{ __('app.receipt_date') }}</th>
                                        <th>{{ __('app.customer') }}</th>
                                        <th>{{ __('app.amount') }}</th>
                                        <th>{{ __('app.action') }}</th>
                                    </tr>
                                    @foreach($group->payments()->with('customer')->get() as $payment)
                                        <tr>
                                            <td>{{ $payment->id }}</td>
                                            <td>{{ $payment->created_at->format('d/m/Y') }}</td>
                                            <td>{{ $payment->customer->first_name }} {{ $payment->customer->last_name }}</td>
                                            <td>{{ $payment->amount }}</td>
                                            <td>
                                                <a class="fa fa-edit btn btn-outline-info" href="{{ route('groups.payment.edit', ['group' => $payment->group_id, 'payment' => $payment->id]) }}"></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <div class="row">
        <div class="col-lg-12">

            <!--begin::Portlet-->
            <div class="k-portlet">
                <div class="k-portlet__head">
                    <div class="k-portlet__head-label">
                        <h3 class="k-portlet__head-title"></h3>
                    </div>
                </div>
                <div class="k-portlet__body">
                    
                </div>
            </div>

        </div>

    </div>

    <div class="modal" id="flightModal" tabindex="-1" role="dialog">
        <form class="modal-dialog" role="document" method="post">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Flight Number</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="flight_no">Flight no</label>
                        <input type="text" class="form-control" id="flight_no" name="flight_no" placeholder="Enter Flight Number">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </form>
    </div>
@endsection